name: Sync FlashPipe CP001 IFlows from Tenant
on:
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    container:
      image: engswee/flashpipe:2.x.x-lite
    env:
      HOST_TMN: ${{ secrets.DEV_HOST_TMN }}
      OAUTH_CLIENTID: ${{ secrets.DEV_USER }}
      OAUTH_CLIENTSECRET: ${{ secrets.DEV_PASSWORD }}
    steps:
      - uses: actions/checkout@v2
      - name: 'Set GIT_SRC_DIR for sync_to_git_repository.sh'
        run: |
          echo "GIT_SRC_DIR=$GITHUB_WORKSPACE/CP001TrainingPackage" >> $GITHUB_ENV
      - name: 'Sync FlashPipeDemo IFlows'
        run: /usr/bin/sync_to_git_repository.sh
        shell: bash
        env:
          PACKAGE_ID: CP001TrainingPackage
          COMMIT_MESSAGE: 'Update FlashPipeDemo package contents'
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
